[features]
seeds = false
skip-lint = false
[programs.localnet]
root_program = "9TgBv6Pqaf7nUjzh3aQMN366EPiiNfft4x9xdC2F6CLe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhrumil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
